// Generated by CoffeeScript 1.10.0
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    console.log('asdf');
    res.send('Hello World!');
  });

  app.listen(3000, function() {
    console.log('Example app listening on port 3000!');
  });


  var request = require('request');

  require('request-debug')(request);
  require('request-debug')(request, function(type, data, r) {
    console.log(type, data, r);
    // put your request or response handling logic here
  });


}).call(this);
