// Generated by CoffeeScript 1.10.0
(function() {
  var StatsD, _, app, debug, express, finalhandler, http, port, responseTime, server, stats;

  _ = require('lodash');

  express = require('express');

  http = require('http');

  debug = require('debug');

  StatsD = require('node-statsd');

  responseTime = require('response-time');

  finalhandler = require('finalhandler');

  port = 5000;


  app = express();

  stats = new StatsD();

  server = http.createServer(app);

  server.listen(port, function() {
    console.log('my app listening on port 80');
  });

  server.on('error', function() {
    console.log('ERRROORR', arguments);
  });

  server.on('listening', function() {
    var addr, bind;
    addr = server.address();
    bind = typeof addr === 'string' ? 'pipe ' + addr : 'port ' + addr.port;
    debug('Listening on ' + bind);
  });

  stats.socket.on('error', function(error) {
    console.error(error.stack);
  });

  app.use(responseTime(function(req, res, time) {
    return console.log(req.method, req.url, res.statusCode, '-', _.round(time, 3));
  }));

  app.get('/', function(req, res) {
    res.send('Hello Worldfdd!');
  });

  module.exports = app;

}).call(this);
